language: python

sudo: required

services:
  - docker

python:
  - "2.7"

before_install:
  # run reszelaz/sardana-test docker container (Debian8 with sardana-deps)
  - docker pull reszelaz/sardana-test
  - docker run -d --name=sardana-test -h sardana-test --volume=`pwd`:/sardana reszelaz/sardana-test
  - sleep 10

script:
  - docker exec sardana-test /bin/bash -c "cd sardana ; python setup.py install"
  - docker exec sardana-test /bin/bash -c "sardanatestsuite"
